module.exports = {
    server: {
        port: 4943,
        hostname: 'localhost',
        styles_directory: 'client/styles',
        scripts_directory: 'client/scripts',
        static_prefix: '/static',
    },
    forecastio: {
        url: 'https://api.forecast.io/forecast/',
        api_key: '9a53bc525842e37f0d10dd2c650590c3',
        units: 'si',
        temperature_symbol: '°C',
        valid_weekdays: [
            'monday',
            'tuesday',
            'wednesday',
            'thursday',
            'friday',
            'saturday',
            'sunday',
        ],
    },
    geocode: {
        url: 'http://maps.googleapis.com/maps/api/geocode/json',
        irrelevant_address_components: [
            'street',
            'street_number',
            'route',
            'intersection',
            'premise',
            'subpremise',
            'postal_code',
            'natural_feature',
            'park',
            'point_of_interest',
        ],
    },
    icons: {
        summary_icons: {
            'clear-day': 'wi-day-sunny',
            'clear-night': 'wi-night-clear',
            'rain': 'wi-rain',
            'snow': 'wi-snow',
            'sleet': 'wi-sleet',
            'wind': 'wi-strong-wind',
            'fog': 'wi-fog',
            'cloudy': 'wi-cloudy',
            'partly-cloudy-day': 'wi-day-cloudy',
            'partly-cloudy-night': 'wi-night-alt-cloudy',
        },
        wind_speed_icon: 'wi-beafort-%d',
        wind_speed_max: 12,
        beaufort_constant: 0.836,
        wind_direction_icon: '_%d-deg',
        wind_direction_num: 24,
        moon_icon: 'wi-moon-%s',
        moon_phase_num: 28,
        moon_perfect_phases: [
            'new',
            'first-quarter',
            'moon-full',
            '3rd-quarter',
        ],
        moon_intermediate_phases: [
            'waxing-cresent-%d',
            'waxing-gibbous-%d',
            'waning-gibbous-%d',
            'waning-crescent-%d',
        ],
    },
};
